FROM arm32v7/node:8.6.0 
MAINTAINER Stefan Biermann 

ENV TZ 'Europe/Berlin'

ADD alexa-fhem-0.3.5.tgz /
RUN mv package alexa-fhem && cd alexa-fhem &&\
	npm install && mkdir ~/.alexa && mkdir /config &&\
    cp config-sample.json /config/config.json && \
    ln -s /config/config.json ~/.alexa/config.json && \
    ln -s /config/key.pem /alexa-fhem/key.pem &&\ 
    ln -s /config/cert.pem /alexa-fhem/cert.pem

COPY start.sh /
VOLUME /config
EXPOSE 3000
CMD ["/start.sh"]
